spring:
  application:
    name: nba-server
  config:
    import: optional:configserver:http://www.timerrivers.com:8888
  cloud:
    config:
      label: master
      name: nba-server
    bus:
      enabled: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}:${random.value}
    prefer-ip-address: true
    ip-address: 139.9.206.164
    health-check-url-path: /actuator/health
  client:
    serviceUrl:
      defaultZone: http://139.9.206.164:8761/eureka/
